spring.application.name=GramSevaPortal

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=${APP_JWT_SECRET:a-string-secret-at-least-256-bits-long}
app.jwt.exp-ms=${APP_JWT_EXP_MS:86400000}

# CORS
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5500}

# SendGrid
sendgrid.api.key=${SENDGRID_API_KEY}
app.mail.from=${APP_MAIL_FROM}

# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}
